# Generated by Django 5.0 on 2023-12-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="comments",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
