# Generated by Django 5.0 on 2024-01-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_checkout_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Science Fiction", "Science Fiction"),
                    ("Fantasy", "Fantasy"),
                    ("Mystery", "Mystery"),
                    ("Thriller", "Thriller"),
                    ("Romance", "Romance"),
                    ("Historical Fiction", "Historical Fiction"),
                    ("Non-Fiction", "Non-Fiction"),
                    ("Biography", "Biography"),
                    ("Self-Help", "Self-Help"),
                    ("Horror", "Horror"),
                ],
                max_length=60,
            ),
        ),
    ]
