# Generated by Django 5.0 on 2024-01-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_books_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="quantity",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
