# Generated by Django 5.0 on 2024-01-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_checkout_quantity_remove_checkout_book_checkout_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
            ),
        ),
    ]
