# Generated by Django 5.0 on 2024-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_reviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="uri",
            field=models.URLField(
                default="https://drive.google.com/file/d/1diTegPLe9x7QkzG5AuXO9W1YgBPHqf4M/view?usp=drive_link"
            ),
        ),
    ]
