# Generated by Django 4.2.9 on 2024-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0011_books_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="uri",
            field=models.FileField(upload_to="books/"),
        ),
    ]
